import { z } from "zod";
import { themes } from "@/lib/site";

/**
 * Frontmatter contracts for every content type.
 *
 * These are deliberately strict. Blog and media files are generated by
 * automation (the phase 4 archive import and the phase 5 paste-a-link skills),
 * so a malformed file should fail the build loudly rather than silently
 * publish an entry with a missing date or a broken link.
 */

/**
 * Accepts YYYY-MM-DD strings and the Date objects gray-matter yields for
 * unquoted dates. The custom message matters: with hundreds of generated files
 * the default ("expected date, received Date") is impossible to act on.
 */
const dateField = z.union([z.string(), z.date()]).transform((value, ctx) => {
  const parsed = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    ctx.addIssue({
      code: "custom",
      message: `Invalid date ${JSON.stringify(value)} — expected YYYY-MM-DD.`,
    });
    return z.NEVER;
  }
  return parsed;
});

const themeField = z.enum(themes);

/** How the post originated — recorded so future filtering never needs a re-import. */
export const postKinds = [
  "text",
  "photo",
  "share",
  "life-event",
  "other",
] as const;

export const imageSchema = z.object({
  src: z.string().min(1),
  alt: z.string().default(""),
  width: z.number().int().positive().optional(),
  height: z.number().int().positive().optional(),
});

export const postFrontmatterSchema = z.object({
  title: z.string().min(1),
  date: dateField,
  theme: themeField,
  /** Content language, per-entry. Defaults to the site's content locale. */
  lang: z.string().default("ru"),
  summary: z.string().optional(),
  /** Post type from the Facebook archive import (handoff doc §5c). */
  kind: z.enum(postKinds).default("text"),
  images: z.array(imageSchema).default([]),
  /** Link back to the original Facebook post, where known. */
  sourceUrl: z.string().url().optional(),
  /** Set false to keep an entry out of the build without deleting the file. */
  published: z.boolean().default(true),
});

export type PostFrontmatter = z.infer<typeof postFrontmatterSchema>;

export const mediaFrontmatterSchema = z.object({
  title: z.string().min(1),
  date: dateField,
  /** The external URL this entry points at — the whole point of a media entry. */
  url: z.string().url(),
  /** Publication, show or channel name. */
  source: z.string().optional(),
  description: z.string().optional(),
  theme: themeField.optional(),
  lang: z.string().default("ru"),
  published: z.boolean().default(true),
});

export type MediaFrontmatter = z.infer<typeof mediaFrontmatterSchema>;

export const eventSchema = z.object({
  title: z.string().min(1),
  date: dateField,
  location: z.string().optional(),
  url: z.string().url().optional(),
});

export const eventsFileSchema = z.array(eventSchema);

export type SiteEvent = z.infer<typeof eventSchema>;
